### ISSUE TITLE
Relación Ingrediente - Alimento

### ISSUE THREAD

**Issue by TobiasDemoor** [maualima/PDTS-Spring-Celiaquia#9]
https://github.com/maualima/PDTS-Spring-Celiaquia/blob/dd403bb06c972d31172297812af4e5fc2b61eea5/src/main/java/com/mau/spring/model/Ingrediente.java#L17-L18

¿Siendo que Puede haber muchos Ingredientes que hacen referencia al mismo alimento no sería más correcto utilizar la anotación @ManyToOne? Con la configuración actual posiblemente se encuentren alimentos duplicados en la bd al crear distintos ingredientes con el mismo alimento.

**Comment by mau-lima** [comment]
Confirmo, corregimos
